### ISSUE TITLE
[Suggestion] Debugger additions

### ISSUE THREAD

**Issue by JesterWizard** [Veslyquix/ASM#2]
I've been using it for a few days and here are some things I think would be good to add:

- Set the unit's current HP
- Set the unit's support levels
- Set the unit's weapon ranks
- Set the unit's item IDs to 0 (if you want to empty their inventory).

Might add to this later.

**Comment by Veslyquix** [comment]
When you change their max hp, it also sets their current hp to that value. 

I agree about the rest but I might not have time to add new menus for a while. You can probably change MinItem to 0 instead of 1 pretty easily if you like.

**Comment by JesterWizard** [comment]
> When you change their max hp, it also sets their current hp to that value.

There should be an option to set the current HP seperately to test skills or other effects that require a certain amount of HP to be lost.

**Comment by Veslyquix** [comment]
done
